USE [master]
GO
/****** Object:  Database [KosiNwabuezeBattleships2017]    Script Date: 6/27/2017 1:27:17 PM ******/
CREATE DATABASE [KosiNwabuezeBattleships2017]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KosiNwabuezeBattleships2017', FILENAME = N'C:\Users\creat\KosiNwabuezeBattleships2017.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'KosiNwabuezeBattleships2017_log', FILENAME = N'C:\Users\creat\KosiNwabuezeBattleships2017_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KosiNwabuezeBattleships2017].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET ARITHABORT OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET  ENABLE_BROKER 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET  MULTI_USER 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET DB_CHAINING OFF 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET QUERY_STORE = OFF
GO
USE [KosiNwabuezeBattleships2017]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
ALTER DATABASE [KosiNwabuezeBattleships2017] SET  READ_WRITE 
GO
